//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RIDE_IN_TROLLEY = "ride_in_trolley";
        
        public const string PISTOL_RECOIL = "pistol_recoil";
        
        public const string THROW = "throw";
        
        public const string TELEPORT = "teleport";
        
        public const string ARROW_HIT = "arrow_hit";
    }
}
